In [60]:
#Calculation and understanding of SVD. most PCA is mostly covariance A = (AT.A/n-1)
#when the number of features are more than the number of samples PCA turns singular and thus becomes noninvertible
#secondly instead of calculating the variance for all the features and calculating the eigen vectors, it is calculated on reduced features

In [2]:
import numpy as np

In [13]:
def find_nice_A(shortcut=False, lim=1000000):
    """ 
    find a 'nice' original array A, such that the eigenvalues
    of U and V are integers.
    (require discriminant of the determinant characteristic eqn
        to be +positive perfect square)
    """
    if shortcut:
        A = np.array([[5, 0, 2, 4]
                     ,[2, 6, 1, 2]])
    else:
        A = np.random.randint(0,9,(2,4))
    
    roots = set(np.arange(50))

    for i in range(lim):
        U = A @ A.T

        a = 1
        b = - U[0,0] - U[1,1]
        c = (U[0,0] * U[1,1]) - (U[0,1] * U[1,0])

        if np.sqrt((b**2) - (4*a*c)) in roots:
            
            V = A.T @ A

            a = 1
            b = - V[0,0] - V[1,1]
            c = (V[0,0] * V[1,1]) - (V[0,1] * V[1,0])

            if np.sqrt((b**2) - (4*a*c)) in roots:
                
                if (np.sum(A==0) == 1) & (np.sum(A[0,:] - A[1,:]) == 0):
                
                    return A, i
    
        A = np.random.randint(0,9,(2,4))       

    return 'not found', lim

In [19]:
A,i = find_nice_A(shortcut=True)

In [31]:
AAT = A@A.T
ATA = A.T@A

In [45]:
lmbU,U=np.linalg.eig(AAT)
lmbV,V=np.linalg.eig(ATA)
np.shape(V)
#the eigen values are calculated and found to be the same.

(4, 4)

In [56]:
#A = U.S.VT we are decomposing the matrix into several matrices 

#Calculating S out of it

S= np.sqrt(np.diag(lmbV))[:2,:]
S

array([[ 8.06225775,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  5.        ,  0.        ,  0.        ]])

In [49]:
A1=U@S@V.T


In [58]:
-A1.round()

array([[ 5.,  0.,  2.,  4.],
       [ 2.,  6.,  1.,  2.]])

In [57]:
A

array([[5, 0, 2, 4],
       [2, 6, 1, 2]])

In [59]:
#The negative sign is due to the factor that eigen values are not stable and changes in sign
#http://blog.applied.ai/feature-reduction-using-svd/